//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Tim_Viec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infomationWork
    {
        public int id { get; set; }
        public string nameWork { get; set; }
        public string nameCompany { get; set; }
        public string href { get; set; }
        public string country { get; set; }
        public string salary { get; set; }
        public string date { get; set; }
    }
}
